logger:
  level: DEBUG

psql:
  dsn: "host=postgres port=5432 user=user password=qwerty dbname=otus_calendar sslmode=disable"
  migration: migrations

dbType: sql

server:
  port: 8090
  host: calendar

grpsServer:
  port: 50051
  host: calendar
